joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

camera_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: astra_joint
  pid: {p: 2.0, i: 0.0, d: 0.0}
  
front_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_wheel_hinge
  pid: {p: 2.0, i: 0.0, d: 0.0}
  
front_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_wheel_hinge
  pid: {p: 2.0, i: 0.0, d: 0.0}
  
rear_left_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_left_wheel_hinge
  pid: {p: 2.0, i: 0.0, d: 0.0}
  
rear_right_wheel_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_right_wheel_hinge
  pid: {p: 2.0, i: 0.0, d: 0.0}
